name: Terraform デプロイ
on:
  push:
    branches:
      - main  # mainブランチへのプッシュ時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC認証に必要な権限
      contents: read   # リポジトリ内容の読み取り権限

    steps:
    # コードのチェックアウト
    - name: コードのチェックアウト
      uses: actions/checkout@v2

    # AWS認証情報の設定
    - name: AWS認証情報の設定
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::203918871690:role/Github_Action
        role-session-name: GitHubActionsSession
        aws-region: ap-northeast-1  # 東京リージョンの場合

    # Terraformの初期化
    - name: Terraform初期化
      run: terraform init

    # Terraformプラン
    - name: Terraformプラン
      run: terraform plan

    # Terraformデプロイ（オプション）
    - name: Terraformデプロイ
      if: github.ref == 'refs/heads/main'  # mainブランチの場合のみ実行
      run: terraform apply -auto-approve